version: "3"
services:
  web:
    container_name: UserManager
    restart: always
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/base/app
      - /base/app/node_modules
    links:
      - mongo
    command: nodemon -L

  mongo:
    container_name: mongo
    image: mongo
    volumes:
      - mongodata:/base/app/data
    ports:
      - "27017:27017"

  adminmongo:
    image: "mrvautin/adminmongo"
    ports:
     - "1234:1234"

volumes:
  mongodata:
    driver: local